CREATE TABLE "BOOK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "TITLE" VARCHAR(255) NOT NULL,
    "AUTHOR" VARCHAR(255) NOT NULL
);

CREATE TABLE "CUSTOMER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FULLNAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL
);

CREATE TABLE "RENT" (
);